#!/usr/bin/env bash
# One-click installer for TimeSphere's on-prem/single-org Docker Compose shape (see
# docs/DEPLOYMENT.md's "Shape 1"). Native bash — no Node required just to bootstrap, since
# everything the app itself needs runs inside the containers Docker builds.
#
# What this does: checks Docker/Compose are present, generates a root .env (the file
# docker-compose.yml reads its variables from) with strong random secrets if one doesn't already
# exist, brings the stack up, waits for the API's health check, then runs the one-time seed.
#
# What this deliberately does NOT do: install Docker itself, touch anything outside this repo,
# or silently overwrite an existing .env — re-running this script against an already-configured
# deployment just brings the stack up again.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

log()  { printf '\033[1;36m==>\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$1"; }
fail() { printf '\033[1;31m[error]\033[0m %s\n' "$1" >&2; exit 1; }

log "Checking for Docker..."
if ! command -v docker >/dev/null 2>&1; then
  fail "Docker isn't installed. Install it first: https://docs.docker.com/get-docker/"
fi
if ! docker compose version >/dev/null 2>&1; then
  fail "The 'docker compose' plugin isn't available. Install it: https://docs.docker.com/compose/install/"
fi
log "Docker $(docker --version | sed 's/Docker version //') with Compose plugin found."

ENV_FILE="$ROOT_DIR/.env"
if [ -f "$ENV_FILE" ]; then
  log ".env already exists — leaving it as-is. Delete it first if you want fresh generated secrets."
else
  log "Generating .env with strong random secrets..."

  if command -v openssl >/dev/null 2>&1; then
    rand_b64() { openssl rand -base64 48 | tr -d '\n'; }
    rand_hex32() { openssl rand -hex 32 | tr -d '\n'; }
  else
    warn "openssl not found — falling back to /dev/urandom (still cryptographically strong)."
    rand_b64() { head -c 48 /dev/urandom | base64 | tr -d '\n'; }
    rand_hex32() { head -c 32 /dev/urandom | xxd -p | tr -d '\n'; }
  fi

  printf 'This installer targets a local/trial deployment by default.\n'
  read -r -p "Public URL for the web app [http://localhost:5173]: " WEB_ORIGIN_INPUT
  WEB_ORIGIN_VALUE="${WEB_ORIGIN_INPUT:-http://localhost:5173}"
  read -r -p "Public URL for the API (used as the SSO callback base) [${WEB_ORIGIN_VALUE}]: " APP_BASE_URL_INPUT
  APP_BASE_URL_VALUE="${APP_BASE_URL_INPUT:-$WEB_ORIGIN_VALUE}"

  # Hex, not base64: this value gets embedded unencoded in a mysql:// DSN below, and base64's
  # alphabet includes '/' and '+' — either would corrupt the URL (a literal '/' reads as a path
  # separator). Hex is alphanumeric-only, so it's always URL-safe regardless of what it rolls.
  MYSQL_ROOT_PASSWORD_VALUE="$(rand_hex32)"

  cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ") — see docs/DEPLOYMENT.md for what
# each of these does. docker-compose.yml reads this file automatically.
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD_VALUE}
MYSQL_DATABASE=timesheet_portal
DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD_VALUE}@mysql:3306/timesheet_portal
CONTROL_DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD_VALUE}@mysql:3306/timesphere_control
DEFAULT_ORG_SLUG=default
JWT_ACCESS_SECRET=$(rand_b64)
JWT_REFRESH_SECRET=$(rand_b64)
PLATFORM_ADMIN_JWT_SECRET=$(rand_b64)
ENCRYPTION_KEY=$(rand_hex32)
WEB_ORIGIN=${WEB_ORIGIN_VALUE}
APP_BASE_URL=${APP_BASE_URL_VALUE}
ANTHROPIC_API_KEY=
EOF
  log ".env written to $ENV_FILE"
fi

log "Building and starting the stack (this can take a few minutes on first run)..."
docker compose up -d --build

log "Waiting for the API to become healthy..."
API_READY=false
for _ in $(seq 1 60); do
  if curl -fsS http://localhost:4000/health >/dev/null 2>&1; then
    API_READY=true
    break
  fi
  sleep 3
done

if [ "$API_READY" != true ]; then
  warn "API didn't report healthy within 3 minutes — check 'docker compose logs api'."
  warn "Migrations run automatically on boot; a slow first-pull of the mysql:8.4 image is the usual cause."
else
  log "API is healthy."
fi

log "Running the one-time seed (roles, permissions, control-plane plan tiers, platform-admin account)..."
if docker compose exec -T api npm run control:seed -w apps/api && docker compose exec -T api npm run seed -w apps/api; then
  log "Seed complete."
else
  warn "Seeding failed or was already run — if this is a fresh install, check 'docker compose logs api' and re-run:"
  warn "  docker compose exec api npm run control:seed -w apps/api && docker compose exec api npm run seed -w apps/api"
fi

cat <<EOF

$(printf '\033[1;32m✓ TimeSphere is up.\033[0m')

  Web app:            ${WEB_ORIGIN_VALUE:-http://localhost:5173}
  Platform admin:     ${WEB_ORIGIN_VALUE:-http://localhost:5173}/platform-admin/login
  Platform admin login: platform-admin@timesphere.local / PlatformAdmin@12345 (change this)

Next steps are in docs/DEPLOYMENT.md — first org admin login, SMTP setup, backups, and (if you
outgrow one company) the SaaS multi-org shape.
EOF
