<#
.SYNOPSIS
  One-click installer for TimeSphere's on-prem/single-org Docker Compose shape (see
  docs/DEPLOYMENT.md's "Shape 1"). Native PowerShell - no Node required just to bootstrap.

.DESCRIPTION
  Checks Docker/Compose are present, generates a root .env (the file docker-compose.yml reads
  its variables from) with strong random secrets if one doesn't already exist, brings the stack
  up, waits for the API's health check, then runs the one-time seed.

  Deliberately does NOT install Docker Desktop itself, touch anything outside this repo, or
  overwrite an existing .env -re-running this script against an already-configured deployment
  just brings the stack up again.
#>

$ErrorActionPreference = "Stop"
$RootDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $RootDir

function Write-Step($Message) { Write-Host "==> $Message" -ForegroundColor Cyan }
function Write-Warn($Message) { Write-Host "[warn] $Message" -ForegroundColor Yellow }
function Write-Fail($Message) { Write-Host "[error] $Message" -ForegroundColor Red; exit 1 }

Write-Step "Checking for Docker..."
$dockerCmd = Get-Command docker -ErrorAction SilentlyContinue
if (-not $dockerCmd) {
  Write-Fail "Docker isn't installed. Install Docker Desktop: https://docs.docker.com/desktop/install/windows-install/"
}
try { docker compose version | Out-Null } catch {
  Write-Fail "The 'docker compose' plugin isn't available. Update Docker Desktop to a recent version."
}
Write-Host "Docker with Compose plugin found."

function New-RandomBase64([int]$Bytes) {
  $buffer = New-Object byte[] $Bytes
  [System.Security.Cryptography.RandomNumberGenerator]::Fill($buffer)
  return [Convert]::ToBase64String($buffer)
}

function New-RandomHex32() {
  $buffer = New-Object byte[] 32
  [System.Security.Cryptography.RandomNumberGenerator]::Fill($buffer)
  return ($buffer | ForEach-Object { $_.ToString("x2") }) -join ""
}

$EnvFile = Join-Path $RootDir ".env"
if (Test-Path $EnvFile) {
  Write-Step ".env already exists -leaving it as-is. Delete it first if you want fresh generated secrets."
  $WebOrigin = "http://localhost:5173"
} else {
  Write-Step "Generating .env with strong random secrets..."

  Write-Host "This installer targets a local/trial deployment by default."
  $WebOriginInput = Read-Host "Public URL for the web app [http://localhost:5173]"
  $WebOrigin = if ([string]::IsNullOrWhiteSpace($WebOriginInput)) { "http://localhost:5173" } else { $WebOriginInput }
  $AppBaseUrlInput = Read-Host "Public URL for the API (used as the SSO callback base) [$WebOrigin]"
  $AppBaseUrl = if ([string]::IsNullOrWhiteSpace($AppBaseUrlInput)) { $WebOrigin } else { $AppBaseUrlInput }

  # Hex, not base64: this value gets embedded unencoded in a mysql:// DSN below, and base64's
  # alphabet includes '/' and '+' - either would corrupt the URL (a literal '/' reads as a path
  # separator). Hex is alphanumeric-only, so it's always URL-safe regardless of what it rolls.
  $MysqlRootPassword = New-RandomHex32
  $GeneratedAt = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

  $envContent = @"
# Generated by install.ps1 on $GeneratedAt -see docs/DEPLOYMENT.md for what each of these does.
# docker-compose.yml reads this file automatically.
MYSQL_ROOT_PASSWORD=$MysqlRootPassword
MYSQL_DATABASE=timesheet_portal
DATABASE_URL=mysql://root:$MysqlRootPassword@mysql:3306/timesheet_portal
CONTROL_DATABASE_URL=mysql://root:$MysqlRootPassword@mysql:3306/timesphere_control
DEFAULT_ORG_SLUG=default
JWT_ACCESS_SECRET=$(New-RandomBase64 48)
JWT_REFRESH_SECRET=$(New-RandomBase64 48)
PLATFORM_ADMIN_JWT_SECRET=$(New-RandomBase64 48)
ENCRYPTION_KEY=$(New-RandomHex32)
WEB_ORIGIN=$WebOrigin
APP_BASE_URL=$AppBaseUrl
ANTHROPIC_API_KEY=
"@
  # UTF8 no-BOM -a BOM in this file would end up as literal bytes inside the first env var's
  # value once Compose parses it.
  [System.IO.File]::WriteAllText($EnvFile, $envContent, (New-Object System.Text.UTF8Encoding($false)))
  Write-Host ".env written to $EnvFile"
}

Write-Step "Building and starting the stack (this can take a few minutes on first run)..."
docker compose up -d --build

Write-Step "Waiting for the API to become healthy..."
$apiReady = $false
for ($i = 0; $i -lt 60; $i++) {
  try {
    $response = Invoke-WebRequest -Uri "http://localhost:4000/health" -UseBasicParsing -TimeoutSec 3
    if ($response.StatusCode -eq 200) { $apiReady = $true; break }
  } catch {}
  Start-Sleep -Seconds 3
}

if (-not $apiReady) {
  Write-Warn "API didn't report healthy within 3 minutes -check 'docker compose logs api'."
  Write-Warn "Migrations run automatically on boot; a slow first-pull of the mysql:8.4 image is the usual cause."
} else {
  Write-Host "API is healthy."
}

Write-Step "Running the one-time seed (roles, permissions, control-plane plan tiers, platform-admin account)..."
docker compose exec -T api npm run control:seed -w apps/api
docker compose exec -T api npm run seed -w apps/api
if ($LASTEXITCODE -ne 0) {
  Write-Warn "Seeding failed or was already run -if this is a fresh install, check 'docker compose logs api' and re-run:"
  Write-Warn "  docker compose exec api npm run control:seed -w apps/api; docker compose exec api npm run seed -w apps/api"
} else {
  Write-Host "Seed complete."
}

Write-Host ""
Write-Host "TimeSphere is up." -ForegroundColor Green
Write-Host ""
Write-Host "  Web app:              $WebOrigin"
Write-Host "  Platform admin:       $WebOrigin/platform-admin/login"
Write-Host "  Platform admin login: platform-admin@timesphere.local / PlatformAdmin@12345 (change this)"
Write-Host ""
Write-Host "Next steps are in docs/DEPLOYMENT.md -first org admin login, SMTP setup, backups, and" -ForegroundColor DarkGray
Write-Host "(if you outgrow one company) the SaaS multi-org shape." -ForegroundColor DarkGray
