/**
 * WHAT: the AI usage breakdown as a real Excel workbook, for offline analysis or a board report —
 * mirrors change-export.service.ts's shape: a Summary sheet, a provider×model Usage sheet, and a
 * day×feature×provider×model Daily detail sheet, all built from the SAME underlying query result
 * so no two sheets can disagree about what's included or what it cost.
 *
 * WHY NO ROW CAP, unlike the change register export: the Usage sheet has one row per distinct
 * provider×model pair actually used in the range — realistically a handful to a few dozen. The
 * Daily detail sheet is finer-grained but still bounded by this app's own documented AI call
 * volume (see ai.service.ts's "AI call volume here is low" reasoning for the same trade-off in
 * the on-screen trend charts) — never the thousands a ticket or change export can reach.
 * `X-Export-Rows-Included` is still sent for scriptability, but there is no truncation to warn about.
 */
import ExcelJS from "exceljs";

export interface AiUsageExportRow {
  provider: string;
  model: string;
  calls: number;
  successCount: number;
  failureCount: number;
  successRatePct: number | null;
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  avgLatencyMs: number | null;
  latencyMeasuredCalls: number;
  costUsd: number;
  costSharePct: number;
}

/** One day's use of one feature by one provider×model — the export's answer to "which provider
 *  and model handled which AI feature, and on which day, and what did it cost". `costSharePct` is
 *  computed against the SAME grand total as the Usage sheet's rows (passed in, not re-derived),
 *  so the two sheets' percentages always agree even though they group the data differently. */
export interface AiUsageDailyExportRow {
  date: string;
  feature: string;
  provider: string;
  model: string;
  calls: number;
  successCount: number;
  failureCount: number;
  successRatePct: number | null;
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  avgLatencyMs: number | null;
  latencyMeasuredCalls: number;
  costUsd: number;
}

export interface AiUsageExportContext {
  generatedBy: string;
  workspace: string;
  from: string;
  to: string;
  /** null = every feature included, not filtered to one. */
  feature: string | null;
}

export async function buildAiUsageWorkbook(rows: AiUsageExportRow[], dailyRows: AiUsageDailyExportRow[], ctx: AiUsageExportContext): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "TimeSphere";
  wb.created = new Date();

  const totalCalls = rows.reduce((sum, r) => sum + r.calls, 0);
  const totalCostUsd = rows.reduce((sum, r) => sum + r.costUsd, 0);

  const summary = wb.addWorksheet("Summary");
  summary.columns = [
    { header: "Measure", key: "measure", width: 34 },
    { header: "Value", key: "value", width: 46 }
  ];
  summary.addRows([
    { measure: "Workspace", value: ctx.workspace },
    { measure: "Generated by", value: ctx.generatedBy },
    { measure: "Generated at", value: new Date().toISOString().slice(0, 16).replace("T", " ") + " UTC" },
    { measure: "Range", value: `${ctx.from} to ${ctx.to}` },
    { measure: "Feature filter", value: ctx.feature ?? "All features" },
    { measure: "Provider × model rows", value: rows.length },
    { measure: "Daily detail rows", value: dailyRows.length },
    { measure: "Total calls", value: totalCalls },
    { measure: "Total cost (USD, estimated)", value: totalCostUsd.toFixed(4) }
  ]);
  summary.getRow(1).font = { bold: true };

  const usage = wb.addWorksheet("Usage");
  usage.columns = [
    { header: "Provider", key: "provider", width: 20 },
    { header: "Model", key: "model", width: 30 },
    { header: "Calls", key: "calls", width: 10 },
    { header: "Successes", key: "successCount", width: 12 },
    { header: "Failures", key: "failureCount", width: 10 },
    { header: "Success rate", key: "successRatePct", width: 14 },
    { header: "Input tokens", key: "inputTokens", width: 14 },
    { header: "Output tokens", key: "outputTokens", width: 14 },
    { header: "Total tokens", key: "totalTokens", width: 14 },
    { header: "Avg latency (ms)", key: "avgLatencyMs", width: 16 },
    { header: "Latency measured on", key: "latencyMeasuredCalls", width: 18 },
    { header: "Cost (USD, estimated)", key: "costUsd", width: 16 },
    { header: "% of total cost", key: "costSharePct", width: 14 }
  ];
  for (const row of rows) {
    usage.addRow({ ...row, avgLatencyMs: row.avgLatencyMs ?? "not measured", successRatePct: row.successRatePct ?? "n/a" });
  }
  usage.getRow(1).font = { bold: true };
  usage.views = [{ state: "frozen", ySplit: 1 }];
  usage.autoFilter = { from: "A1", to: { row: 1, column: usage.columns.length } };

  const daily = wb.addWorksheet("Daily detail");
  daily.columns = [
    { header: "Date", key: "date", width: 12 },
    { header: "Feature", key: "feature", width: 22 },
    { header: "Provider", key: "provider", width: 20 },
    { header: "Model", key: "model", width: 30 },
    { header: "Calls", key: "calls", width: 10 },
    { header: "Successes", key: "successCount", width: 12 },
    { header: "Failures", key: "failureCount", width: 10 },
    { header: "Success rate", key: "successRatePct", width: 14 },
    { header: "Input tokens", key: "inputTokens", width: 14 },
    { header: "Output tokens", key: "outputTokens", width: 14 },
    { header: "Total tokens", key: "totalTokens", width: 14 },
    { header: "Avg latency (ms)", key: "avgLatencyMs", width: 16 },
    { header: "Latency measured on", key: "latencyMeasuredCalls", width: 18 },
    { header: "Cost (USD, estimated)", key: "costUsd", width: 16 },
    { header: "% of total cost", key: "costSharePct", width: 14 }
  ];
  for (const row of dailyRows) {
    const costSharePct = totalCostUsd === 0 ? 0 : Number(((row.costUsd / totalCostUsd) * 100).toFixed(1));
    daily.addRow({ ...row, avgLatencyMs: row.avgLatencyMs ?? "not measured", successRatePct: row.successRatePct ?? "n/a", costSharePct });
  }
  daily.getRow(1).font = { bold: true };
  daily.views = [{ state: "frozen", ySplit: 1 }];
  daily.autoFilter = { from: "A1", to: { row: 1, column: daily.columns.length } };

  return Buffer.from(await wb.xlsx.writeBuffer());
}
