/**
 * WHAT: the change register as a real document — an Excel workbook and a PDF, alongside the CSV.
 *
 * WHY THREE FORMATS AND ONE QUERY: they answer the same question for three audiences. CSV is for a
 * spreadsheet somebody will pivot; the workbook is for a manager who wants it readable without
 * formatting it first; the PDF is what gets attached to an audit response. All three are fed by the
 * SAME rows the caller already fetched, so no two formats can disagree about which changes matched —
 * the rule the timesheet exports were built around and the reason they share a query builder.
 *
 * WHY THE PDF STATES ITS OWN LIMITS: a truncated export that looks complete is the failure these
 * exports exist to avoid. The row cap is printed in the header and the footer, and every format
 * returns the same `X-Export-*` headers, so a script and a human both find out.
 */
import ExcelJS from "exceljs";

/** One change, flattened to the columns a change record is actually judged on. */
export interface ChangeExportRow {
  changeKey: string;
  project: string;
  title: string;
  changeKind: string;
  category: string | null;
  environment: string;
  state: string;
  impact: string;
  likelihood: string;
  riskLevel: string;
  riskScore: number;
  requestedBy: string;
  implementer: string | null;
  decidedBy: string | null;
  decision: string | null;
  decisionComments: string | null;
  plannedStart: Date | null;
  plannedEnd: Date | null;
  actualStart: Date | null;
  actualEnd: Date | null;
  outcome: string | null;
  submittedAt: Date | null;
  approvedAt: Date | null;
  closedAt: Date | null;
}

export interface ExportContext {
  /** Who ran it and when — an export with no provenance is a screenshot. */
  generatedBy: string;
  workspace: string;
  truncated: boolean;
  rowCap: number;
}

const stamp = (d: Date | null): string => (d ? d.toISOString().slice(0, 16).replace("T", " ") : "");

/* ------------------------------------------------------------------ *
 * Excel
 * ------------------------------------------------------------------ */

/**
 * A real workbook, not a CSV with an .xlsx extension: frozen header, typed columns, filters, and a
 * summary sheet built from the SAME capped row set as the detail sheet — so a truncated export can
 * never ship a summary that does not add up, which is the specific bug the timesheet workbook was
 * fixed for.
 */
export async function buildChangeWorkbook(rows: ChangeExportRow[], ctx: ExportContext): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "TimeSphere";
  wb.created = new Date();

  const summary = wb.addWorksheet("Summary");
  summary.columns = [
    { header: "Measure", key: "measure", width: 34 },
    { header: "Value", key: "value", width: 46 }
  ];
  const byState = new Map<string, number>();
  const byRisk = new Map<string, number>();
  let failed = 0;
  for (const r of rows) {
    byState.set(r.state, (byState.get(r.state) ?? 0) + 1);
    byRisk.set(r.riskLevel, (byRisk.get(r.riskLevel) ?? 0) + 1);
    if (r.outcome === "FAILED" || r.outcome === "ROLLED_BACK") failed += 1;
  }
  const closed = rows.filter((r) => r.closedAt).length;

  summary.addRows([
    { measure: "Workspace", value: ctx.workspace },
    { measure: "Generated by", value: ctx.generatedBy },
    { measure: "Generated at", value: new Date().toISOString().slice(0, 16).replace("T", " ") + " UTC" },
    { measure: "Changes in this export", value: rows.length },
    // Stated even when false, so the reader never has to wonder whether the line was omitted or the
    // export was complete.
    { measure: "Truncated", value: ctx.truncated ? `Yes — capped at ${ctx.rowCap} rows` : "No" },
    { measure: "", value: "" },
    // Null, never 0: "no change has closed yet" and "every closed change succeeded" are different
    // facts, and a 0% failure rate over an empty set is the kind of number that gets quoted.
    { measure: "Change failure rate", value: closed === 0 ? "No closed changes yet" : `${Math.round((failed / closed) * 100)}% (${failed} of ${closed})` }
  ]);
  for (const [state, count] of [...byState].sort()) summary.addRow({ measure: `State — ${state}`, value: count });
  for (const [risk, count] of [...byRisk].sort()) summary.addRow({ measure: `Risk — ${risk}`, value: count });
  summary.getRow(1).font = { bold: true };

  const detail = wb.addWorksheet("Changes");
  detail.columns = [
    { header: "Change", key: "changeKey", width: 26 },
    { header: "Project", key: "project", width: 26 },
    { header: "Title", key: "title", width: 44 },
    { header: "Type", key: "changeKind", width: 12 },
    { header: "Category", key: "category", width: 16 },
    { header: "Environment", key: "environment", width: 14 },
    { header: "State", key: "state", width: 18 },
    { header: "Impact", key: "impact", width: 10 },
    { header: "Likelihood", key: "likelihood", width: 12 },
    { header: "Risk", key: "riskLevel", width: 10 },
    { header: "Score", key: "riskScore", width: 8 },
    { header: "Requested by", key: "requestedBy", width: 20 },
    { header: "Implementer", key: "implementer", width: 20 },
    { header: "Decided by", key: "decidedBy", width: 20 },
    { header: "Decision", key: "decision", width: 12 },
    { header: "Comments", key: "decisionComments", width: 40 },
    { header: "Planned start", key: "plannedStart", width: 18 },
    { header: "Planned end", key: "plannedEnd", width: 18 },
    { header: "Actual start", key: "actualStart", width: 18 },
    { header: "Actual end", key: "actualEnd", width: 18 },
    { header: "Outcome", key: "outcome", width: 22 },
    { header: "Submitted", key: "submittedAt", width: 18 },
    { header: "Approved", key: "approvedAt", width: 18 },
    { header: "Closed", key: "closedAt", width: 18 }
  ];
  for (const r of rows) {
    detail.addRow({
      ...r,
      plannedStart: stamp(r.plannedStart),
      plannedEnd: stamp(r.plannedEnd),
      actualStart: stamp(r.actualStart),
      actualEnd: stamp(r.actualEnd),
      submittedAt: stamp(r.submittedAt),
      approvedAt: stamp(r.approvedAt),
      closedAt: stamp(r.closedAt)
    });
  }
  detail.getRow(1).font = { bold: true };
  detail.views = [{ state: "frozen", ySplit: 1 }];
  detail.autoFilter = { from: "A1", to: { row: 1, column: detail.columns.length } };

  return Buffer.from(await wb.xlsx.writeBuffer());
}

/* ------------------------------------------------------------------ *
 * PDF
 * ------------------------------------------------------------------ */

const PAGE_MARGIN = 36;
const INK = "#0F172A";
const MUTED = "#64748B";
const RULE = "#E2E8F0";

/** Column widths, landscape A4 minus margins. Tuned so the title gets the slack — it is the only
 *  column whose content varies, and truncating it is what makes a register unreadable. */
const COLUMNS: Array<{ key: keyof ChangeExportRow | "window"; label: string; width: number }> = [
  { key: "changeKey", label: "Change", width: 118 },
  { key: "title", label: "Title", width: 190 },
  { key: "changeKind", label: "Type", width: 58 },
  { key: "environment", label: "Env", width: 62 },
  { key: "state", label: "State", width: 84 },
  { key: "riskLevel", label: "Risk", width: 46 },
  { key: "riskScore", label: "Score", width: 34 },
  { key: "requestedBy", label: "Requested by", width: 82 },
  { key: "decidedBy", label: "Decided by", width: 82 },
  { key: "window", label: "Window (UTC)", width: 114 }
];

/**
 * Renders the register into an already-piped document.
 *
 * The caller owns the stream — same split as `security-report-pdf.service.ts`, which is what lets the
 * controller stay a router and keeps `bufferPages` (and therefore "Page N of M") possible.
 */
export function renderChangeRegisterPdf(doc: PDFKit.PDFDocument, rows: ChangeExportRow[], ctx: ExportContext): void {
  const startX = PAGE_MARGIN;
  const usableBottom = doc.page.height - PAGE_MARGIN - 24;

  doc.fillColor(INK).font("Helvetica-Bold").fontSize(16).text("Change register", startX, PAGE_MARGIN);
  doc.font("Helvetica").fontSize(9).fillColor(MUTED);
  doc.text(`${ctx.workspace} · generated by ${ctx.generatedBy} · ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC`, startX, doc.y + 2);
  doc.text(
    ctx.truncated
      ? `Showing the first ${rows.length} changes — this export is capped at ${ctx.rowCap} rows and is NOT complete.`
      : `${rows.length} change${rows.length === 1 ? "" : "s"}, complete.`,
    startX,
    doc.y + 2
  );

  let y = doc.y + 10;

  const header = () => {
    doc.font("Helvetica-Bold").fontSize(7.5).fillColor(MUTED);
    let x = startX;
    for (const col of COLUMNS) {
      doc.text(col.label.toUpperCase(), x, y, { width: col.width - 6, ellipsis: true });
      x += col.width;
    }
    y += 12;
    doc.moveTo(startX, y).lineTo(startX + COLUMNS.reduce((s, c) => s + c.width, 0), y).strokeColor(RULE).stroke();
    y += 5;
  };
  header();

  doc.font("Helvetica").fontSize(7.5);
  for (const row of rows) {
    if (y > usableBottom) {
      doc.addPage({ layout: "landscape", size: "A4", margin: PAGE_MARGIN });
      y = PAGE_MARGIN;
      header();
      doc.font("Helvetica").fontSize(7.5);
    }
    let x = startX;
    for (const col of COLUMNS) {
      const value =
        col.key === "window"
          ? row.plannedStart
            ? `${stamp(row.plannedStart)} → ${stamp(row.plannedEnd)}`
            : "not scheduled"
          : (row[col.key as keyof ChangeExportRow] ?? "");
      // High risk is the one value worth finding by eye on a printed page.
      const emphasise = col.key === "riskLevel" && row.riskLevel === "HIGH";
      doc.fillColor(emphasise ? "#B3372F" : INK).text(String(value), x, y, { width: col.width - 6, ellipsis: true, lineBreak: false });
      x += col.width;
    }
    y += 13;
  }

  // "Page N of M" needs every page to exist first, which is why the caller opens the document with
  // `bufferPages: true`.
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);
    doc.font("Helvetica").fontSize(7.5).fillColor(MUTED);
    doc.text(
      `${ctx.truncated ? `Capped at ${ctx.rowCap} rows · ` : ""}Page ${i + 1} of ${range.count}`,
      PAGE_MARGIN,
      doc.page.height - PAGE_MARGIN - 10,
      { width: doc.page.width - PAGE_MARGIN * 2, align: "right" }
    );
  }
}
