/**
 * WHAT: the project list as a real workbook — two sheets, one question each.
 *
 *  - "Projects": one row per project, exactly the columns the CSV carried, so the sheet answers
 *    "what projects exist and who is on them".
 *  - "Hierarchy": one row per module and per submodule, each carrying its project's code, name,
 *    status and created date, so the sheet answers "what is inside each project" and can be
 *    filtered or pivoted on any of it.
 *
 * WHY TWO SHEETS AND NOT ONE WIDE ONE: a module row and a project row are different grains, and a
 * single sheet mixing them forces either a repeated project block per module (which double-counts
 * every project-level figure the moment somebody sums a column) or blank cells that break every
 * filter. Two sheets, each at one grain, is how the change-management workbook next door solved
 * the same problem, and this mirrors it.
 *
 * The two sheets are built from the SAME row set, so they can never disagree about which projects
 * are in the file.
 */
import ExcelJS from "exceljs";

export interface ProjectExportRow {
  code: string;
  name: string;
  status: string;
  description: string | null;
  createdAt: Date;
  team: Array<{ name: string }>;
  modules: Array<{ name: string; createdAt: Date; submodules: Array<{ name: string; createdAt: Date }> }>;
}

const stamp = (d: Date) => d.toISOString().slice(0, 10);

export async function buildProjectWorkbook(rows: ProjectExportRow[], generatedBy: string): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "TimeSphere";
  wb.created = new Date();

  // ── Sheet 1: the project list, the same columns the CSV export carries.
  const projects = wb.addWorksheet("Projects");
  projects.columns = [
    { header: "Code", key: "code", width: 16 },
    { header: "Name", key: "name", width: 36 },
    { header: "Status", key: "status", width: 12 },
    { header: "Modules", key: "modules", width: 10 },
    { header: "Submodules", key: "submodules", width: 12 },
    { header: "Team size", key: "teamSize", width: 10 },
    { header: "Team", key: "team", width: 48 },
    { header: "Description", key: "description", width: 48 },
    { header: "Created", key: "created", width: 12 }
  ];
  for (const p of rows) {
    projects.addRow({
      code: p.code,
      name: p.name,
      status: p.status,
      modules: p.modules.length,
      submodules: p.modules.reduce((sum, m) => sum + m.submodules.length, 0),
      teamSize: p.team.length,
      team: p.team.map((t) => t.name).join("; "),
      description: p.description ?? "",
      created: stamp(p.createdAt)
    });
  }
  projects.getRow(1).font = { bold: true };
  projects.views = [{ state: "frozen", ySplit: 1 }];
  projects.autoFilter = { from: "A1", to: { row: 1, column: projects.columns.length } };

  // ── Sheet 2: the hierarchy, one row per module and per submodule. A project with no modules
  // still gets one row, so the sheet lists every project the first sheet does.
  const hierarchy = wb.addWorksheet("Hierarchy");
  hierarchy.columns = [
    { header: "Project code", key: "code", width: 16 },
    { header: "Project name", key: "project", width: 36 },
    { header: "Module", key: "module", width: 32 },
    { header: "Submodule", key: "submodule", width: 32 },
    { header: "Level", key: "level", width: 12 },
    { header: "Project status", key: "status", width: 14 },
    { header: "Project created", key: "projectCreated", width: 16 },
    { header: "Created", key: "created", width: 12 }
  ];
  for (const p of rows) {
    if (p.modules.length === 0) {
      hierarchy.addRow({ code: p.code, project: p.name, module: "", submodule: "", level: "Project", status: p.status, projectCreated: stamp(p.createdAt), created: stamp(p.createdAt) });
      continue;
    }
    for (const m of p.modules) {
      hierarchy.addRow({ code: p.code, project: p.name, module: m.name, submodule: "", level: "Module", status: p.status, projectCreated: stamp(p.createdAt), created: stamp(m.createdAt) });
      for (const sm of m.submodules) {
        hierarchy.addRow({ code: p.code, project: p.name, module: m.name, submodule: sm.name, level: "Submodule", status: p.status, projectCreated: stamp(p.createdAt), created: stamp(sm.createdAt) });
      }
    }
  }
  hierarchy.getRow(1).font = { bold: true };
  hierarchy.views = [{ state: "frozen", ySplit: 1 }];
  hierarchy.autoFilter = { from: "A1", to: { row: 1, column: hierarchy.columns.length } };

  // ── Provenance, on its own small sheet rather than as a footer row that breaks the filters.
  const about = wb.addWorksheet("About");
  about.columns = [
    { header: "Measure", key: "k", width: 24 },
    { header: "Value", key: "v", width: 40 }
  ];
  about.addRows([
    { k: "Generated by", v: generatedBy },
    { k: "Generated at", v: `${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC` },
    { k: "Projects", v: rows.length },
    { k: "Modules", v: rows.reduce((s, p) => s + p.modules.length, 0) },
    { k: "Submodules", v: rows.reduce((s, p) => s + p.modules.reduce((t, m) => t + m.submodules.length, 0), 0) }
  ]);
  about.getRow(1).font = { bold: true };

  return Buffer.from(await wb.xlsx.writeBuffer());
}
