apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "timesphere.fullname" . }}-api
  labels:
    {{- include "timesphere.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "timesphere.selectorLabels" (dict "Release" .Release "Chart" .Chart "component" "api") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "timesphere.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- if .Values.image.pullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      {{- end }}
      containers:
        - name: api
          image: {{ include "timesphere.image" (dict "root" . "component" "api") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4000
          envFrom:
            - configMapRef:
                name: {{ include "timesphere.fullname" . }}-config
            - secretRef:
                name: {{ .Values.existingSecretName }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ include "timesphere.fullname" . }}-api-uploads
