apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "timesphere.fullname" . }}-api-uploads
  labels:
    {{- include "timesphere.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.api.uploadsVolumeSize }}
