apiVersion: v1
kind: Service
metadata:
  name: {{ include "timesphere.fullname" . }}-web
  labels:
    {{- include "timesphere.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    {{- include "timesphere.selectorLabels" (dict "Release" .Release "Chart" .Chart "component" "web") | nindent 4 }}
