apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "timesphere.fullname" . }}-web
  labels:
    {{- include "timesphere.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  {{- if not .Values.web.autoscaling.enabled }}
  replicas: {{ .Values.web.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "timesphere.selectorLabels" (dict "Release" .Release "Chart" .Chart "component" "web") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "timesphere.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- if .Values.image.pullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      {{- end }}
      containers:
        - name: web
          image: {{ include "timesphere.image" (dict "root" . "component" "web") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 5
            periodSeconds: 20
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 3
            periodSeconds: 10
