-- AlterTable
ALTER TABLE `GlobalAISettings` ADD COLUMN `apiKey` TEXT NULL,
    ADD COLUMN `baseUrl` VARCHAR(300) NULL,
    ADD COLUMN `provider` ENUM('ANTHROPIC', 'OPENAI_COMPATIBLE') NOT NULL DEFAULT 'ANTHROPIC';
